name: TryHackMe Update Badge

on:
  schedule:
    - cron: '0 0 * * *'   # κάθε μέρα 00:00 UTC
  workflow_dispatch:

permissions:
  contents: write          # για να μπορεί να κάνει commit την εικόνα

jobs:
  tryhackme-badge-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: p4p1/tryhackme-badge-workflow@main
        with:
          username: "Naki500"                 # το THM username σου
          image_path: assets/thm_propic.png # που θα σωθεί η εικόνα
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
